// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjU8Nc9hOKjKT3vQ90WZqGEARaEuo4FWY',
    appId: '1:624999107309:web:706e48aaeaf51e41e19ae4',
    messagingSenderId: '624999107309',
    projectId: 'mobile-app-development-b304f',
    authDomain: 'mobile-app-development-b304f.firebaseapp.com',
    storageBucket: 'mobile-app-development-b304f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMVlRwgrI70_KNydZZnN8d2CVMpyELj-E',
    appId: '1:624999107309:android:ade0be4de2d51a80e19ae4',
    messagingSenderId: '624999107309',
    projectId: 'mobile-app-development-b304f',
    storageBucket: 'mobile-app-development-b304f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgI2q04gT6IyV2n5u_6D7ijifQ5O1kAU',
    appId: '1:624999107309:ios:015941dbc4df1d20e19ae4',
    messagingSenderId: '624999107309',
    projectId: 'mobile-app-development-b304f',
    storageBucket: 'mobile-app-development-b304f.firebasestorage.app',
    iosBundleId: 'com.example.massa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtgI2q04gT6IyV2n5u_6D7ijifQ5O1kAU',
    appId: '1:624999107309:ios:015941dbc4df1d20e19ae4',
    messagingSenderId: '624999107309',
    projectId: 'mobile-app-development-b304f',
    storageBucket: 'mobile-app-development-b304f.firebasestorage.app',
    iosBundleId: 'com.example.massa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjU8Nc9hOKjKT3vQ90WZqGEARaEuo4FWY',
    appId: '1:624999107309:web:1b1941b6e34221ace19ae4',
    messagingSenderId: '624999107309',
    projectId: 'mobile-app-development-b304f',
    authDomain: 'mobile-app-development-b304f.firebaseapp.com',
    storageBucket: 'mobile-app-development-b304f.firebasestorage.app',
  );
}
